name: ecommerce_admin_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.5.0-2.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  iconly: ^1.0.1
  fancy_shimmer_image: ^2.0.3
  dynamic_height_grid_view: ^0.0.4
  card_slider: ^1.0.5
  card_swiper: ^3.0.1
  ionicons: ^0.2.2
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      - assets/images/bag/
      - assets/images/banner/
      - assets/images/categories/
      - assets/images/categories/112/
      - assets/images/profile/
      - assets/images/profile/512/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
